function nv_chang_cat(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_cat&catid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_cat_result")}
function nv_chang_cat_result(a){a=a.split("_");"OK"!=a[0]&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);a=parseInt(a[1]);nv_show_list_cat(a)}function nv_show_list_cat(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_cat&parentid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_cat(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_cat&catid="+a,"","nv_del_cat_result");return!1}
function nv_del_cat_result(a){a=a.split("_");"OK"==a[0]?(a=parseInt(a[1]),nv_show_list_cat(a)):"ERR"==a[0]&&"CAT"==a[1]?alert(a[2]):"ERR"==a[0]&&"ROWS"==a[1]?confirm(a[4])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_cat&catid="+a[2]+"&delallcheckss="+a[3],"cat-delete-area",""):alert(nv_is_del_confirm[2]);return!1}
function nv_chang_group(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_group&groupid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_group_result")}
function nv_chang_group_result(a){a=a.split("_");"OK"!=a[0]&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);a=parseInt(a[1]);nv_show_list_group(a)}function nv_show_list_group(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_group&parentid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_group(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_group&groupid="+a,"","nv_del_group_result");return!1}
function nv_del_group_result(a){a=a.split("_");"OK"==a[0]?(a=parseInt(a[1]),nv_show_list_group(a)):"ERR"==a[0]&&"CAT"==a[1]?alert(a[2]):"ERR"==a[0]&&"ROWS"==a[1]?confirm(a[4])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_group&groupid="+a[2]+"&delallcheckss="+a[3],"group-delete-area",""):alert(nv_is_del_confirm[2]);return!1}
function nv_chang_sources(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_source&sourceid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_sources_result")}
function nv_chang_sources_result(a){"OK"!=a.split("_")[0]&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_source()}function nv_show_list_source(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_source&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_source(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_source&sourceid="+a,"","nv_del_source_result");return!1}function nv_del_source_result(a){a=a.split("_");"OK"==a[0]?nv_show_list_source():"ERR"==a[0]?alert(a[1]):alert(nv_is_del_confirm[2]);return!1}
function nv_del_block_cat(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_block_cat&bid="+a,"","nv_del_block_cat_result");return!1}function nv_del_block_cat_result(a){a=a.split("_");"OK"==a[0]?nv_show_list_block_cat():"ERR"==a[0]?alert(a[1]):alert(nv_is_del_confirm[2]);return!1}
function nv_chang_block_cat(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=chang_block_cat&bid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_block_cat_result")}
function nv_chang_block_cat_result(a){"OK"!=a.split("_")[0]&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_block_cat()}function nv_show_list_block_cat(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_block_cat&num="+nv_randomPassword(8),"module_show_list")}
function nv_chang_block(a,b,c){nv_settimeout_disable("id_weight_"+b,5E3);var d=document.getElementById("id_weight_"+b).options[document.getElementById("id_weight_"+b).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block&id="+b+"&bid="+a+"&&mod="+c+"&new_vid="+d+"&num="+nv_randomPassword(8),"","nv_chang_block_result")}
function nv_chang_block_result(a){a=a.split("_");"OK"!=a[0]&&alert(nv_is_change_act_confirm[2]);a=parseInt(a[1]);nv_show_list_block(a)}function nv_show_list_block(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_block&bid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_block_list(a,b){var c="",d=a["idcheck[]"];if(d.length)for(var e=0;e<d.length;e++)d[e].checked&&(c=c+","+d[e].value);else d.checked&&(c=c+","+d.value);""!=c&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block&del_list="+c+"&bid="+b+"&num="+nv_randomPassword(8),"","nv_chang_block_result")}
function nv_main_action(a,b,c){var d=a["idcheck[]"],a="";if(d.length)for(var e=0;e<d.length;e++)d[e].checked&&(a=a+d[e].value+",");else d.checked&&(a=a+d.value+",");""!=a?(c=document.getElementById("action").value,"delete"==c?confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&listid="+a+"&checkss="+b,"","nv_del_content_result"):"addtoblock"==c?window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+
"=block&listid="+a+"#add":"publtime"==c?window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=publtime&listid="+a+"&checkss="+b:"exptime"==c&&(window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=exptime&listid="+a+"&checkss="+b)):alert(c)}
function nv_del_content(a,b){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&id="+a+"&checkss="+b,"","nv_del_content_result");return!1}function nv_check_movecat(a,b){if(0==a.catidnews.value)return alert(b),!1}
function nv_del_content_result(a){a=a.split("_");"OK"==a[0]?window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=items":"ERR"==a[0]?alert(a[1]):alert(nv_is_del_confirm[2]);return!1}
function create_keywords(){var a=strip_tags(document.getElementById("keywords").value);""!=a&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=keywords&content="+encodeURIComponent(a),"","res_keywords");return!1}function res_keywords(a){"n/a"!=a?document.getElementById("keywords").value=a:document.getElementById("keywords").value="";return!1}
function nv_sh(a,b){3==document.getElementById(a).options[document.getElementById(a).selectedIndex].value?nv_show_hidden(b,1):nv_show_hidden(b,0);return!1}function findValue(a){return null==a?alert("No match!"):a.extra?a.extra[0]:a.selectValue}function selectItem(a){sValue=findValue(a)}function formatItem(a){return a[0]+" ("+a[1]+")"}function nv_chang_pays(a,b,c,d){b=$(b).val();$.ajax({type:"POST",url:c,data:"oid="+a+"&w="+b,success:function(){window.location=d}})}
function ChangeActive(a,b){var c=$(a).attr("id");$.ajax({type:"POST",url:b,data:"id="+c,success:function(a){alert(a)}})}function get_alias(){var a=strip_tags(document.getElementById("idtitle").value);""!=a&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=alias&title="+encodeURIComponent(a),"","res_get_alias");return!1}
function res_get_alias(a){""!=a?document.getElementById("idalias").value=a:document.getElementById("idalias").value="";return!1}
function nv_add_otherimage(){var a='<tr><td><input class="txt" value="" name="otherimage[]" id="otherimage_'+file_items+'" style="width : 80%" maxlength="255" />',a=a+('&nbsp;<input type="button" value="'+file_selectfile+'" name="selectfile" onclick="nv_open_browse_file( \''+nv_base_adminurl+"index.php?"+nv_name_variable+"=upload&popup=1&area=otherimage_"+file_items+"&path="+file_dir+"&type=file&currentpath="+currentpath+"', 'NVImg', 850, 400, 'resizable=no,scrollbars=no,toolbar=no,location=no,status=no' ); return false; \" /></td></tr>");
$("#otherimage").append(a);file_items++}function nv_getcatalog(a){a=$(a).val();a=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=getcatalog&pid="+a;$("#vcatid").load(a)}function nv_getgroup(a){a=$(a).val();a=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=getgroup&cid="+a+"&inrow="+inrow;$("#listgroupid").load(a)};