function sendrating(a,b,c){(1==b||2==b||3==b||4==b||5==b)&&nv_ajax("post",nv_siteroot+"index.php",nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=rating&id="+a+"&checkss="+c+"&point="+b,"stringrating","")}
function sendcommment(a,b,c){var d=document.getElementById("commentseccode_iavim"),e=strip_tags(document.getElementById("commentcontent").value);nv_name_check(d)?""==e?(alert(nv_content),document.getElementById("commentcontent").focus()):(document.getElementById("buttoncontent").disabled=!0,nv_ajax("post",nv_siteroot+"index.php",nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=postcomment&code="+d.value+"&id="+a+"&checkss="+b+"&content="+encodeURIComponent(e),
"","nv_commment_result")):(error=nv_error_seccode.replace(/\[num\]/g,c),alert(error),d.focus())}function nv_commment_result(a){nv_change_captcha("vimg","commentseccode_iavim");a=a.split("_");"OK"==a[0]?(document.getElementById("commentcontent").value="",nv_show_comment(a[1],a[2],a[3]),alert(a[4])):"ERR"==a[0]?alert(a[1]):alert(nv_content_failed);nv_set_disable_false("buttoncontent");return!1}
function nv_show_comment(a,b,c){nv_ajax("get",nv_siteroot+"index.php",nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=comment&id="+a+"&checkss="+b+"&page="+c,"showcomment","")}function remove_text(){document.getElementById("to_date").value="";document.getElementById("from_date").value=""}
function nv_del_content(a,b,c){confirm(nv_is_del_confirm[0])&&nv_ajax("post",c+"index.php",nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&id="+a+"&checkss="+b,"","nv_del_content_result");return!1}function nv_del_content_result(a){a=a.split("_");"OK"==a[0]?window.location.href=strHref:"ERR"==a[0]?alert(a[1]):alert(nv_is_del_confirm[2]);return!1}function share_twitter(){u=location.href;t=document.title;window.open("http://twitter.com/home?status="+encodeURIComponent(u))}
function share_facebook(){u=location.href;t=document.title;window.open("http://www.facebook.com/share.php?u="+encodeURIComponent(u)+"&t="+encodeURIComponent(t))}function share_google(){u=location.href;t=document.title;window.open("http://www.google.com/bookmarks/mark?op=edit&bkmk="+encodeURIComponent(u)+"&title="+t+"&annotation="+t)}function share_buzz(){u=location.href;t=document.title;window.open("http://buzz.yahoo.com/buzz?publisherurn=DanTri&targetUrl="+encodeURIComponent(u))}
function tabview_aux(a,b){for(var c=document.getElementById(a),d=c.firstChild;"Tabs"!=d.className;)d=d.nextSibling;var e=d.firstChild,d=0;do"A"==e.tagName&&(d++,e.href="javascript:tabview_switch('"+a+"', "+d+");",e.className=d==b?"Active":"",e.blur());while(e=e.nextSibling);for(c=c.firstChild;"Pages"!=c.className;)c=c.nextSibling;c=c.firstChild;d=0;do"Page"==c.className&&(d++,c.style.display=d==b?"block":"none");while(c=c.nextSibling)}
function SetCookieForTabView(a,b,c){var d=new Date,e=new Date;if(null==c||0==c)c=1;e.setTime(d.getTime()+864E5*c);document.cookie=a+"="+escape(b)+";expires="+e.toGMTString()}function ReadCookie(a){var b=""+document.cookie,c=b.indexOf(a);if(-1==c||""==a)return"";var d=b.indexOf(";",c);-1==d&&(d=b.length);return unescape(b.substring(c+a.length+1,d))}function tabview_switch(a,b){tabview_aux(a,b);SetCookieForTabView("tvID",b,36)}
function tabview_initialize(a){tvID2=ReadCookie("tvID");-1==tvID2||""==tvID2?(SetCookieForTabView("tvID",1,36),tabview_aux(a,1)):tabview_aux(a,tvID2)}
function cartorder(a){a=$(a).attr("id");$.ajax({type:"GET",url:nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=setcart&id="+a+"&nocache="+(new Date).getTime(),data:"",success:function(a){a=a.split("_")[1];if(null!=a){for(var c=a.indexOf("#@#");-1!=c;)a=a.replace("#@#","_"),c=a.indexOf("#@#");alert_msg(a);linkloadcart=nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+
"=loadcart";$("#cart_"+nv_module_name).load(linkloadcart)}}})}
function cartorder_detail(a){var b=$("#pnum").val(),a=$(a).attr("id");$.ajax({type:"POST",url:nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=setcart&id="+a+"&nocache="+(new Date).getTime(),data:"num="+b,success:function(a){a=a.split("_")[1];if(null!=a){for(var b=a.indexOf("#@#");-1!=b;)a=a.replace("#@#","_"),b=a.indexOf("#@#");alert_msg(a);linkloadcart=nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+
"="+nv_module_name+"&"+nv_fc_variable+"=loadcart";$("#cart_"+nv_module_name).load(linkloadcart)}}})}function alert_msg(a){$("#msgshow").html(a);$("#msgshow").show("slide").delay(3E3).hide("slow")}
function tooltip_shop(){$(".tip_trigger").hover(function(){tip=$(this).find(".tip");tip.show()},function(){tip.hide()}).mousemove(function(a){var b=a.pageX+20,c=a.pageY+20,d=tip.width(),e=tip.height(),f=$(window).width()-(b+d),g=$(window).height()-(c+e);20>f&&(b=a.pageX-d-20);20>g&&(c=a.pageY-e-20);tip.css({top:c,left:b})})}
function checknum(){var a=$("#price1").val(),b=$("#price2").val();""==b&&(b=0);b<a&&(document.getElementById("price2").value="");isNaN(a)?(alert(isnumber),document.getElementById("submit").disabled=!0):0!=b&&isNaN(b)&&(alert(isnumber),document.getElementById("submit").disabled=!0)}function cleartxtinput(a,b){$("#"+a).focusin(function(){var a=$(this).val();b==a&&$(this).val("")});$("#"+a).focusout(function(){""==$(this).val()&&$(this).val(b)})}
function onsubmitsearch(){var a=$("#keyword").val(),b=$("#price1").val();null==b&&(b="");var c=$("#price2").val();null==c&&(c="");var d=$("#sourceid").val(),e=$("#typemoney").val();null==e&&(e="");var f=$("#cata").val();""==a&&""==b&&""==c&&0==f&&0==d||(window.location.href=nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"=shops&"+nv_fc_variable+"=search_result&keyword="+rawurlencode(a)+"&price1="+b+"&price2="+c+"&typemoney="+e+"&cata="+f+"&sid="+d);return!1}
function onsubmitsearch1(){var a=$("#keyword1").val(),b=$("#price11").val();null==b&&(b="");var c=$("#price21").val();null==c&&(c="");var d=$("#sourceid1").val(),e=$("#typemoney1").val();null==e&&(e="");var f=$("#cata1").val();""==a&&""==b&&""==c&&0==f&&0==d||(window.location.href=nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=search_result&keyword="+rawurlencode(a)+"&price1="+b+"&price2="+c+"&typemoney="+e+"&cata="+f+"&sid="+
d);return!1};